alias gopen='gnome-open'
alias robotinossh='ssh robotino@robotino'
alias kbaissh='ssh -Y aravind@kbai-development'
alias rosrobotino='export ROS_MASTER_URI=http://10.25.191.144:11311'
alias run-protege='$HOME/protege/run.sh'
alias cugrep='grep -nrHI --exclude-dir=.svn --exclude-dir=.git'
alias run-serc-cont='docker exec -i -t serc.v12 /bin/bash'
